### ISSUE TITLE
Tree visualization block.

### ISSUE THREAD

**Issue by ItIsMrLaG** [spbu-coding-2022/trees-1#24]
---
## Description:   
It is necessary to implement a toolkit based on the use of **Jetpack Compose Multiplatform** for rendering three trees (_AVL, BIN, RB_).

---
## Tasks:  

- [x]  Come up with a way to draw nodes that allows you to move them with the mouse.
- [x]  Think about the part of the architecture responsible for rendering.
- [x]  Rendering with relationships, no positioning.
- [x]  Add Positioning to Rendering
- [x]  Write a design for rendering
- [ ]  fix errors in drawing nodes with one child
- [ ] Implement zoom
- [x] Implement scroll
